server:
  port: 8089
  servlet:
    context-path: /mobile
  tomcat:
    protocol-header: X-Forwarded-Proto
spring:
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
logging:
  config: classpath:logback.xml